---
- hosts: digitalocean

  vars:
    do_token: 760554437f0d7b2af9262563d6458dfd7d4c7f93d912fb3ce487d1d3ee4d54fc

  tasks:


  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/vishal


  - name: Delete master
    digital_ocean: >
      state=absent
      command=droplet
      name=m1
      unique_name=yes
      size_id=2gb
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: m1


  - name: Delete worker
    digital_ocean: >
      state=absent
      command=droplet
      name=n1
      unique_name=yes
      size_id=2gb
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: n1

  - name: Delete key exists at DigitalOcean
    digital_ocean: >
      state=absent
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/vishal.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

