---
- hosts: digitalocean

  vars:
    do_token: $DO_API_TOKEN

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/vishal

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/vishal.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

  - name: Create master
    digital_ocean: >
      state=present
      command=droplet
      name=m1
      unique_name=yes
      size_id=2gb
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: m1

  - debug: msg="IP is {{ m1.droplet.ip_address }}"

  - name: Create worker
    digital_ocean: >
      state=present
      command=droplet
      name=n1
      unique_name=yes
      size_id=2gb
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: n1

  - debug: msg="IP is {{ n1.droplet.ip_address }}"



